"""
MIGRACIÓN INICIAL: 0001_initial.py
Generado por Django 5.2.5 el 24 de agosto de 2025 a las 17:45

PROPÓSITO:
    Crea la estructura inicial de la base de datos para el módulo de inventario.
    Esta es la primera migración que define el modelo Producto.

CAMBIOS:
    - Crea el modelo 'Producto' con los siguientes campos:
        * id: Clave primaria auto-incremental (BigAutoField)
        * nombre: Texto hasta 100 caracteres
        * descripcion: Campo de texto largo opcional
        * precio: Número decimal (máx 10 dígitos, 2 decimales)
        * stock: Número entero positivo para cantidad

NOTA:
    El campo 'stock' fue posteriormente renombrado a 'cantidad_stock' en la migración 0002.
"""

# Generated by Django 5.2.5 on 2025-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migración inicial que crea el modelo Producto en la base de datos.
    """

    # Esta es la primera migración del módulo
    initial = True

    # No depende de ninguna otra migración
    dependencies = [
    ]

    operations = [
        # Operación: Crear el modelo Producto
        migrations.CreateModel(
            name='Producto',
            fields=[
                # ID automático como clave primaria
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Nombre del producto (obligatorio)
                ('nombre', models.CharField(max_length=100)),
                # Descripción opcional del producto
                ('descripcion', models.TextField(blank=True, null=True)),
                # Precio con 2 decimales
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                # Cantidad en stock (solo números positivos)
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
