# Generated by Django 5.2.5 on 2025-09-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock'),
        ),
    ]
