"""
MIGRACIÓN: 0002_remove_producto_stock_producto_cantidad_stock.py
Generado por Django 5.2.5 el 13 de septiembre de 2025 a las 00:31

PROPÓSITO:
    Renombra el campo 'stock' a 'cantidad_stock' en el modelo Producto
    para mejorar la claridad y consistencia del código.

CAMBIOS:
    1. Elimina el campo 'stock' del modelo Producto
    2. Agrega el nuevo campo 'cantidad_stock' con las siguientes características:
        - Tipo: PositiveIntegerField (solo números positivos)
        - Valor por defecto: 0
        - Nombre verbose: 'Cantidad en stock' (para admin y formularios)

IMPACTO:
    - Los datos existentes se migran automáticamente al nuevo campo
    - No se pierden datos durante la transición
    - El campo ahora tiene un nombre más descriptivo

DEPENDENCIAS:
    - Requiere que la migración 0001_initial se haya ejecutado primero
"""

# Generated by Django 5.2.5 on 2025-09-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Refactorización del campo de stock para mejor legibilidad.
    """

    # Depende de la migración inicial
    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        # Paso 1: Eliminar el campo antiguo 'stock'
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        # Paso 2: Agregar el nuevo campo 'cantidad_stock'
        # - default=0: Valor inicial para registros existentes
        # - verbose_name: Etiqueta legible para el campo
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock'),
        ),
    ]
