"""
Migración inicial del módulo de ventas.

FECHA DE CREACIÓN: 24 de agosto de 2025
GENERADA POR: Django 5.2.5

DESCRIPCIÓN:
Primera migración del módulo de ventas. Crea los modelos básicos para
el sistema de punto de venta (POS) y registro de transacciones.

MODELOS CREADOS:
- Venta: Encabezado de la transacción de venta
- DetalleVenta: Líneas de productos vendidos

RELACIONES:
- Venta → Usuario (SET_NULL)
- DetalleVenta → Venta (CASCADE)
- DetalleVenta → Producto (CASCADE)

CAMPOS INICIALES:
Venta:
- id: Primary key automático
- fecha: Timestamp de la venta (auto_now_add)
- usuario: Usuario que registra la venta

DetalleVenta:
- id: Primary key automático
- cantidad: Unidades vendidas
- subtotal: Total de la línea
- producto: Producto vendido
- venta: Venta a la que pertenece

DEPENDENCIAS:
- inventario.0001_initial: Requiere modelo Producto
- auth.Usuario: Modelo de usuario del sistema

NOTAS:
- Los campos total, metodo_pago y precio_unitario se agregan
  en la migración 0002
- Usuario limitado a rol 'cajero' (aunque acepta cualquiera)
"""

# Generated by Django 5.2.5 on 2025-08-24 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Primera migración del módulo
    initial = True

    dependencies = [
        # Requiere que exista el modelo Producto del inventario
        ('inventario', '0001_initial'),
        # Requiere el modelo Usuario personalizado
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ===== CREAR MODELO VENTA =====
        migrations.CreateModel(
            name='Venta',
            fields=[
                # Primary key automático
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Fecha y hora de la venta (se asigna automáticamente)
                ('fecha', models.DateTimeField(auto_now_add=True)),
                
                # Usuario que realiza la venta
                # SET_NULL: la venta permanece si se elimina el usuario
                # limit_choices_to: originalmente para cajeros
                ('usuario', models.ForeignKey(limit_choices_to={'rol': 'cajero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        # ===== CREAR MODELO DETALLEVENTA =====
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                # Primary key automático
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Cantidad de unidades del producto
                ('cantidad', models.PositiveIntegerField()),
                
                # Subtotal de esta línea (cantidad × precio)
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                
                # Producto vendido (CASCADE: se elimina con el producto)
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                
                # Venta a la que pertenece (CASCADE: se elimina con la venta)
                # related_name='detalles': acceso desde Venta con venta.detalles.all()
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
    ]
