"""
Migración: Agregar campos adicionales a Venta y DetalleVenta.

FECHA DE CREACIÓN: 12 de octubre de 2025
GENERADA POR: Django 5.2.5

DESCRIPCIÓN:
Segunda migración del módulo de ventas. Agrega campos necesarios
para completar la funcionalidad del punto de venta.

CAMBIOS REALIZADOS:
1. DetalleVenta.precio_unitario: Precio del producto al momento de la venta
2. Venta.metodo_pago: Forma de pago utilizada (efectivo por defecto)
3. Venta.total: Monto total de la venta

PROPÓSITO DE LOS NUEVOS CAMPOS:

precio_unitario:
- Mantiene histórico del precio al momento de la venta
- Importante porque los precios de productos pueden cambiar
- Permite calcular correctamente el subtotal

metodo_pago:
- Registra la forma de pago (efectivo, tarjeta, transferencia, etc.)
- Útil para reportes de cierre de caja
- Por defecto: 'efectivo'

total:
- Suma de todos los subtotales de los detalles
- Se calcula automáticamente con el método calcular_total()
- Facilita consultas y reportes

IMPACTO EN DATOS EXISTENTES:
- precio_unitario: Se debe proporcionar valor (sin default permanente)
- metodo_pago: Se asigna 'efectivo' a registros existentes
- total: Se asigna 0 a registros existentes (calcular después)

DEPENDENCIAS:
- ventas.0001_initial: Requiere que existan los modelos base
"""

# Generated by Django 5.2.5 on 2025-10-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Requiere la migración inicial de ventas
        ('ventas', '0001_initial'),
    ]

    operations = [
        # ===== AGREGAR CAMPO: DetalleVenta.precio_unitario =====
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario',
            # DecimalField para manejar moneda con precisión
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            # preserve_default=False: el default solo es para la migración
            preserve_default=False,
        ),
        
        # ===== AGREGAR CAMPO: Venta.metodo_pago =====
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            # CharField para almacenar tipo de pago (efectivo, tarjeta, etc.)
            field=models.CharField(default='efectivo', max_length=20),
        ),
        
        # ===== AGREGAR CAMPO: Venta.total =====
        migrations.AddField(
            model_name='venta',
            name='total',
            # DecimalField para manejar moneda con precisión
            # Se calcula sumando los subtotales de los detalles
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
