"""
MIGRACIÓN INICIAL: 0001_initial.py
Generado por Django 5.2.5 el 24 de agosto de 2025 a las 17:45

PROPÓSITO:
    Crea la estructura inicial de la base de datos para el módulo de servicios.
    Esta es la primera migración que define el modelo Servicio base.

CAMBIOS:
    - Crea el modelo 'Servicio' con los siguientes campos:
        * id: Clave primaria auto-incremental (BigAutoField)
        * descripcion: Campo de texto para detalles del servicio
        * costo: Número decimal para precio base (máx 10 dígitos, 2 decimales)
        * fecha: Fecha/hora de creación automática
        * productos: Relación Many-to-Many con inventario.Producto
        * tecnico: Relación ForeignKey con usuarios.Usuario (SET_NULL)

RELACIONES:
    - Depende de 'inventario.0001_initial' (para la relación con Producto)
    - Depende del modelo AUTH_USER_MODEL (para la relación con Usuario)

NOTA:
    - El campo 'nombre' se agregó posteriormente en la migración 0002
    - El campo 'tecnico' originalmente no permitía blank=True (se modificó en 0002)
"""

# Generated by Django 5.2.5 on 2025-08-24 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migración inicial que crea el modelo Servicio en la base de datos.
    """

    # Esta es la primera migración del módulo
    initial = True

    # Depende de otras migraciones
    dependencies = [
        # Requiere que el modelo Producto exista
        ('inventario', '0001_initial'),
        # Requiere el modelo de Usuario configurado en settings
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Operación: Crear el modelo Servicio
        migrations.CreateModel(
            name='Servicio',
            fields=[
                # ID automático como clave primaria
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Descripción del servicio (obligatorio)
                ('descripcion', models.TextField()),
                
                # Costo base del servicio con valor por defecto 0
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                
                # Fecha de creación automática (no editable)
                ('fecha', models.DateTimeField(auto_now_add=True)),
                
                # Relación Many-to-Many con productos del inventario
                # blank=True: Es opcional asociar productos
                ('productos', models.ManyToManyField(blank=True, to='inventario.producto')),
                
                # Relación ForeignKey con Usuario (técnico asignado)
                # SET_NULL: Si se elimina el usuario, el servicio se mantiene pero sin técnico
                # limit_choices_to: Solo permite seleccionar usuarios con rol='tecnico'
                ('tecnico', models.ForeignKey(
                    limit_choices_to={'rol': 'tecnico'}, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
