"""
MIGRACIÓN: 0002_servicio_nombre_alter_servicio_tecnico.py
Generado por Django 5.2.5 el 23 de septiembre de 2025 a las 16:06

PROPÓSITO:
    Mejora el modelo Servicio agregando campo nombre y flexibilizando
    la asignación de técnicos.

CAMBIOS:
    1. Agrega el campo 'nombre' al modelo Servicio:
        - Tipo: CharField con máximo 200 caracteres
        - Valor por defecto: 'Servicio sin nombre'
        - Permite identificar rápidamente cada servicio
    
    2. Modifica el campo 'tecnico' para hacerlo más flexible:
        - Agrega blank=True: Permite que el formulario acepte el campo vacío
        - Mantiene null=True: Permite que la base de datos almacene NULL
        - Facilita crear servicios sin técnico asignado inicialmente

IMPACTO:
    - Los servicios existentes reciben automáticamente el nombre por defecto
    - Los técnicos ahora son completamente opcionales en formularios
    - Mejora la flexibilidad del sistema de asignación

DEPENDENCIAS:
    - Requiere que la migración 0001_initial se haya ejecutado primero
"""

# Generated by Django 5.2.5 on 2025-09-23 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Refactorización del modelo Servicio para mejor usabilidad.
    """

    # Depende de la migración inicial de servicios
    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Paso 1: Agregar campo nombre al servicio
        # default='Servicio sin nombre': Valor para registros existentes
        # max_length=200: Longitud máxima del nombre
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='Servicio sin nombre', max_length=200),
        ),
        
        # Paso 2: Modificar campo técnico para permitir valores en blanco
        # blank=True: El campo puede estar vacío en formularios
        # null=True: Ya estaba presente, permite NULL en base de datos
        # limit_choices_to: Mantiene restricción a usuarios con rol='tecnico'
        migrations.AlterField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(
                blank=True, 
                limit_choices_to={'rol': 'tecnico'}, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
