"""
MIGRACIÓN: 0003_serviciopagado_productoserviciopagado.py
Generado por Django 5.2.6 el 30 de septiembre de 2025 a las 23:35

PROPÓSITO:
    Implementa el sistema completo de cotizaciones y servicios pagados.
    Agrega dos modelos nuevos para gestionar ventas de servicios a clientes.

CAMBIOS:
    1. Crea el modelo 'ServicioPagado':
        - Registra servicios cotizados o pagados a clientes
        - Almacena precios desglosados (servicio, productos, total)
        - Sistema de estados (cotizado/pagado)
        - Fechas de creación y pago
        - Relación con el servicio base
    
    2. Crea el modelo 'ProductoServicioPagado':
        - Tabla intermedia para productos usados en servicios
        - Registra cantidad y precio unitario al momento de la venta
        - Permite mantener historial de precios
        - Relación con ServicioPagado y Producto

FLUJO DE TRABAJO:
    Servicio (catálogo) → ServicioPagado (cotización/venta) → ProductoServicioPagado (detalle)

RELACIONES:
    - ServicioPagado.servicio → Servicio (FK, CASCADE)
    - ProductoServicioPagado.servicio_pagado → ServicioPagado (FK, CASCADE)
    - ProductoServicioPagado.producto → Producto (FK, CASCADE)

DEPENDENCIAS:
    - Requiere 'inventario.0002_remove_producto_stock_producto_cantidad_stock'
    - Requiere 'servicios.0002_servicio_nombre_alter_servicio_tecnico'
"""

# Generated by Django 5.2.6 on 2025-09-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Implementación del sistema de cotizaciones y ventas de servicios.
    """

    # Depende de migraciones anteriores
    dependencies = [
        # Requiere campo cantidad_stock en Producto
        ('inventario', '0002_remove_producto_stock_producto_cantidad_stock'),
        # Requiere campo nombre en Servicio
        ('servicios', '0002_servicio_nombre_alter_servicio_tecnico'),
    ]

    operations = [
        # ========== Operación 1: Crear modelo ServicioPagado ==========
        migrations.CreateModel(
            name='ServicioPagado',
            fields=[
                # ID automático como clave primaria
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Nombre del cliente que solicita el servicio
                ('nombre_cliente', models.CharField(max_length=200)),
                
                # Precio del servicio base (guardado para historial)
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                
                # Suma total de productos utilizados
                ('precio_productos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                
                # Precio total = precio_servicio + precio_productos
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                
                # Estado del servicio: cotizado o pagado
                # choices: Define los valores permitidos
                # default='cotizado': Estado inicial
                ('estado', models.CharField(
                    choices=[('cotizado', 'Cotizado'), ('pagado', 'Pagado')], 
                    default='cotizado', 
                    max_length=20
                )),
                
                # Fecha de creación de la cotización (automática)
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                
                # Fecha de pago (null hasta que se pague)
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                
                # Relación con el servicio del catálogo
                # CASCADE: Si se elimina el servicio base, se eliminan sus ventas
                ('servicio', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    to='servicios.servicio'
                )),
            ],
            options={
                # Nombres para visualización en admin
                'verbose_name': 'Servicio Pagado',
                'verbose_name_plural': 'Servicios Pagados',
            },
        ),
        
        # ========== Operación 2: Crear modelo ProductoServicioPagado ==========
        migrations.CreateModel(
            name='ProductoServicioPagado',
            fields=[
                # ID automático como clave primaria
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Cantidad de unidades del producto utilizadas
                ('cantidad', models.PositiveIntegerField(default=1)),
                
                # Precio del producto al momento de la venta
                # Se guarda para mantener historial aunque el precio cambie
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                
                # Relación con el producto del inventario
                # CASCADE: Si se elimina el producto, se eliminan estos registros
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    to='inventario.producto'
                )),
                
                # Relación con el servicio pagado
                # CASCADE: Si se elimina el servicio, se eliminan sus productos
                # related_name='productos_utilizados': Acceso inverso desde ServicioPagado
                ('servicio_pagado', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='productos_utilizados', 
                    to='servicios.serviciopagado'
                )),
            ],
            options={
                # Nombres para visualización en admin
                'verbose_name': 'Producto en Servicio',
                'verbose_name_plural': 'Productos en Servicios',
            },
        ),
    ]
