# Generated by Django 5.2.6 on 2025-09-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_stock_producto_cantidad_stock'),
        ('servicios', '0002_servicio_nombre_alter_servicio_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_productos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('pagado', 'Pagado')], default='cotizado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Pagado',
                'verbose_name_plural': 'Servicios Pagados',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicioPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('servicio_pagado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='servicios.serviciopagado')),
            ],
            options={
                'verbose_name': 'Producto en Servicio',
                'verbose_name_plural': 'Productos en Servicios',
            },
        ),
    ]
