"""
Migración inicial del modelo Usuario.

FECHA DE CREACIÓN: 24 de agosto de 2025
GENERADA POR: Django 5.2.5

DESCRIPCIÓN:
Esta migración crea el modelo personalizado de Usuario que extiende AbstractUser
de Django. Es la primera migración del módulo de usuarios y establece la base
del sistema de autenticación.

MODELO CREADO:
- Usuario: Modelo personalizado de usuario con campo adicional 'rol'

CARACTERÍSTICAS:
- Hereda todos los campos de AbstractUser (username, email, password, etc.)
- Agrega campo 'rol' con opciones: 'admin' y 'tecnico'
- Incluye validadores de Django para username
- Configurado con UserManager de Django
- Permisos y grupos de Django incluidos

CAMPOS HEREDADOS DE AbstractUser:
- id: Primary key (BigAutoField)
- username: Nombre de usuario único (CharField, 150 chars)
- password: Contraseña hasheada (CharField, 128 chars)
- first_name: Nombre (CharField, 150 chars, opcional)
- last_name: Apellido (CharField, 150 chars, opcional)
- email: Correo electrónico (EmailField, opcional)
- is_staff: Acceso al admin de Django (Boolean, default False)
- is_active: Usuario activo (Boolean, default True)
- is_superuser: Superusuario con todos los permisos (Boolean, default False)
- last_login: Fecha del último inicio de sesión (DateTime, opcional)
- date_joined: Fecha de registro (DateTime, default now)
- groups: Grupos de permisos (ManyToManyField)
- user_permissions: Permisos específicos (ManyToManyField)

CAMPO PERSONALIZADO:
- rol: Rol del usuario (CharField, choices=['admin', 'tecnico'], default='tecnico')

DEPENDENCIAS:
- Requiere la migración 0012 de auth (aumenta max_length de first_name)

IMPACTO:
- Crea tabla usuarios_usuario en la base de datos
- Configura AUTH_USER_MODEL = 'usuarios.Usuario' en settings.py
- Reemplaza el modelo User por defecto de Django
- Las relaciones ForeignKey a User ahora apuntan a usuarios.Usuario

NOTAS:
- Esta es una migración INICIAL, debe ejecutarse antes de cualquier
  otra migración que dependa del modelo Usuario
- No se puede deshacer fácilmente después de crear usuarios en producción
"""

# Generated by Django 5.2.5 on 2025-08-24 17:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    # Marca esta como la primera migración del módulo
    initial = True

    # Dependencias: requiere migración de auth
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Crear modelo Usuario extendiendo AbstractUser
        migrations.CreateModel(
            name='Usuario',
            fields=[
                # ===== CAMPOS AUTOMÁTICOS =====
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # ===== CAMPOS DE AUTENTICACIÓN =====
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                
                # ===== CAMPOS DE PERMISOS =====
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                
                # ===== CAMPOS DE INFORMACIÓN PERSONAL =====
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                
                # ===== CAMPOS DE ESTADO =====
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                
                # ===== CAMPO PERSONALIZADO =====
                # Campo adicional para diferenciar roles en el sistema
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                
                # ===== RELACIONES CON GRUPOS Y PERMISOS =====
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                # Opciones de metadatos del modelo
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                # Utiliza el UserManager de Django para métodos como create_user()
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
